// <auto-generated />
namespace FATEA.ProjetoPoster.DataAccess.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AtribuicaoPoster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AtribuicaoPoster));
        
        string IMigrationMetadata.Id
        {
            get { return "201609281626266_AtribuicaoPoster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
